# -*- coding: utf-8 -*-
import datetime
version = '3.1.0'
plugins = [
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'no', 'certfile': None, 'charset': u'unoa', 'desc': None, 'filename': u'dutchic_aperak*.edi', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': True, 'host': u'', 'idchannel': u'dutchic_aperak_out', 'inorout': u'out', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/dutchic', 'port': 0, 'remove': True, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'botssys/outfile/dutchic', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'no', 'certfile': None, 'charset': u'us-ascii', 'desc': None, 'filename': u'd*.inh', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': True, 'host': u'', 'idchannel': u'dutchic_desadv_in', 'inorout': u'in', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/dutchic/fixed', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'botssys/infile/dutchic/fixed', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'no', 'certfile': None, 'charset': u'unoa', 'desc': None, 'filename': u'dutchic_desadv*.edi', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': True, 'host': u'', 'idchannel': u'dutchic_desadv_out', 'inorout': u'out', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/dutchic', 'port': 0, 'remove': True, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'botssys/outfile/dutchic', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'no', 'certfile': None, 'charset': u'us-ascii', 'desc': None, 'filename': u'i*.inh', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': True, 'host': u'', 'idchannel': u'dutchic_invoic_in', 'inorout': u'in', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/dutchic/fixed', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'botssys/infile/dutchic/fixed', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'no', 'certfile': None, 'charset': u'unoa', 'desc': None, 'filename': u'dutchic_invoic*.edi', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': True, 'host': u'', 'idchannel': u'dutchic_invoic_out', 'inorout': u'out', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/dutchic', 'port': 0, 'remove': True, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'botssys/outfile/dutchic', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'no', 'certfile': None, 'charset': u'us-ascii', 'desc': None, 'filename': u'*.edi', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': True, 'host': u'', 'idchannel': u'dutchic_orders_in', 'inorout': u'in', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/dutchic/edi', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'botssys/infile/dutchic/edi', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'no', 'certfile': None, 'charset': u'iso-8859-1', 'desc': None, 'filename': u'dutchic_orders_*.inh', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': True, 'host': u'', 'idchannel': u'dutchic_orders_out', 'inorout': u'out', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/dutchic', 'port': 0, 'remove': True, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'botssys/outfile/dutchic', 'type': u'file', 'username': u''},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': u'', 'fromeditype': u'edifact', 'frommessagetype': u'ORDERSD96AUNEAN008', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'fixed', 'tomessagetype': u'ordersfixed', 'topartner': None, 'tscript': u'ordersedi2fixedchainaperak'},
{'plugintype': u'translate', 'active': True, 'alt': u'edifactorders2aperak', 'desc': u'', 'fromeditype': u'edifact', 'frommessagetype': u'ORDERSD96AUNEAN008', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'edifact', 'tomessagetype': u'APERAKD96AUN', 'topartner': None, 'tscript': u'ordersedi2aperak'},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': u'', 'fromeditype': u'fixed', 'frommessagetype': u'desadv96fixed', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'edifact', 'tomessagetype': u'DESADVD96AUNEAN005', 'topartner': None, 'tscript': u'desadvfixed2edi'},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': u'', 'fromeditype': u'fixed', 'frommessagetype': u'invoicfixed', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'edifact', 'tomessagetype': u'INVOICD96AUNEAN008', 'topartner': None, 'tscript': u'invoicfixed2edi'},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': None, 'fromchannel': u'dutchic_desadv_in', 'fromeditype': u'fixed', 'frommessagetype': u'desadv96fixed', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'dutchic_desadv', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 1, 'testindicator': u'', 'tochannel': u'dutchic_desadv_out', 'toeditype': u'', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': None, 'fromchannel': u'dutchic_invoic_in', 'fromeditype': u'fixed', 'frommessagetype': u'invoicfixed', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'dutchic_invoic', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 1, 'testindicator': u'', 'tochannel': u'dutchic_invoic_out', 'toeditype': u'', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': None, 'fromchannel': u'dutchic_orders_in', 'fromeditype': u'edifact', 'frommessagetype': u'edifact', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'dutchic_orders', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 1, 'testindicator': u'', 'tochannel': u'dutchic_orders_out', 'toeditype': u'fixed', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': None, 'fromchannel': None, 'fromeditype': u'', 'frommessagetype': u'', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'dutchic_orders', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 2, 'testindicator': u'', 'tochannel': u'dutchic_aperak_out', 'toeditype': u'edifact', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 0, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'ccodetrigger', 'ccodeid': u'aperakrff2qualifer', 'ccodeid_desc': u'BGM.C002.1001 to aperak code'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'aperakrff2qualifer', 'leftcode': u'220', 'rightcode': u'ON'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'aperakrff2qualifer', 'leftcode': u'224', 'rightcode': u'ON'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'aperakrff2qualifer', 'leftcode': u'351', 'rightcode': u'AAK'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'aperakrff2qualifer', 'leftcode': u'35E', 'rightcode': u'AAK'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'aperakrff2qualifer', 'leftcode': u'380', 'rightcode': u'IV'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'aperakrff2qualifer', 'leftcode': u'384', 'rightcode': u'IV'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'aperakrff2qualifer', 'leftcode': u'50E', 'rightcode': u'ON'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'aperakrff2qualifer', 'leftcode': u'83', 'rightcode': u'IV'},
]
