# -*- coding: utf-8 -*-
import datetime
version = '3.1.0'
plugins = [
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'us-ascii', 'desc': u'', 'filename': u'*', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'demo_partner_conversion_in', 'inorout': u'in', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/demo_work_with_partners/partner_conversion', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'us-ascii', 'desc': u'', 'filename': u'{frompartner}_{topartner}_*.{editype}', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'demo_partner_conversion_out', 'inorout': u'out', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/demo_work_with_partners/partner_conversion', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'utf-8', 'desc': u'', 'filename': u'*.xml', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'outbound_asn_in', 'inorout': u'in', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/demo_work_with_partners/asn', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'us-ascii', 'desc': u'', 'filename': u'{topartner}_{datetime:%Y%m%d}_*.x12', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'outbound_asn_out', 'inorout': u'out', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/demo_work_with_partners/outbound_856', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'us-ascii', 'desc': u'', 'filename': u'{topartner}_{datetime:%Y%m%d}_*.x12', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'outbound_asn_out_partner2', 'inorout': u'out', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/demo_work_with_partners/outbound_856', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'us-ascii', 'desc': u'', 'filename': u'{topartner}_pgroupA_{datetime:%Y%m%d}_*.x12', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'outbound_asn_out_pgroupA', 'inorout': u'out', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/demo_work_with_partners/outbound_856', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'partner', 'active': True, 'address1': u'', 'address2': u'', 'address3': u'', 'attr1': u'XXXXXXXXXXXXXXXX', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'cc': u'', 'city': u'', 'countrycode': u'', 'countrysubdivision': u'', 'desc': None, 'enddate': None, 'group': [], 'idpartner': u'PARTNER1', 'isgroup': False, 'mail': u'', 'name': u'Partner 1', 'name1': u'', 'name2': u'', 'name3': u'', 'phone1': u'', 'phone2': u'', 'postalcode': u'', 'rsrv1': None, 'rsrv2': None, 'startdate': None},
{'plugintype': u'partner', 'active': True, 'address1': u'', 'address2': u'', 'address3': u'', 'attr1': u'PARTNER2LOOKUP', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'cc': u'', 'city': u'', 'countrycode': u'', 'countrysubdivision': u'', 'desc': None, 'enddate': None, 'group': [], 'idpartner': u'PARTNER2', 'isgroup': False, 'mail': u'', 'name': u'Partner 2', 'name1': u'', 'name2': u'', 'name3': u'', 'phone1': u'', 'phone2': u'', 'postalcode': u'', 'rsrv1': None, 'rsrv2': None, 'startdate': None},
{'plugintype': u'partner', 'active': True, 'address1': u'', 'address2': u'', 'address3': u'', 'attr1': u'8712345678906', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'cc': u'', 'city': u'', 'countrycode': u'', 'countrysubdivision': u'', 'desc': None, 'enddate': None, 'group': [u'PGROUP_A', u'PGROUP_B'], 'idpartner': u'PARTNER3', 'isgroup': False, 'mail': u'', 'name': u'Partner 3', 'name1': u'', 'name2': u'', 'name3': u'', 'phone1': u'', 'phone2': u'', 'postalcode': u'', 'rsrv1': None, 'rsrv2': None, 'startdate': None},
{'plugintype': u'partner', 'active': True, 'address1': u'', 'address2': u'', 'address3': u'', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'cc': u'', 'city': u'', 'countrycode': u'', 'countrysubdivision': u'', 'desc': None, 'enddate': None, 'group': [], 'idpartner': u'PGROUP_A', 'isgroup': True, 'mail': u'', 'name': u'Partnergroup A', 'name1': u'', 'name2': u'', 'name3': u'', 'phone1': u'', 'phone2': u'', 'postalcode': u'', 'rsrv1': None, 'rsrv2': None, 'startdate': None},
{'plugintype': u'partner', 'active': True, 'address1': u'', 'address2': u'', 'address3': u'', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'cc': u'', 'city': u'', 'countrycode': u'', 'countrysubdivision': u'', 'desc': None, 'enddate': None, 'group': [], 'idpartner': u'PGROUP_B', 'isgroup': True, 'mail': u'', 'name': u'Partnergroup B', 'name1': u'', 'name2': u'', 'name3': u'', 'phone1': u'', 'phone2': u'', 'postalcode': u'', 'rsrv1': None, 'rsrv2': None, 'startdate': None},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': u'', 'fromeditype': u'x12', 'frommessagetype': u'856004010', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'x12', 'tomessagetype': u'856004010', 'topartner': None, 'tscript': u'inn2out'},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': u'', 'fromeditype': u'xml', 'frommessagetype': u'asn', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'x12', 'tomessagetype': u'856004010', 'topartner': None, 'tscript': u'asn_xml2x12_default'},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': u'', 'fromeditype': u'xml', 'frommessagetype': u'asn', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'x12', 'tomessagetype': u'856004010', 'topartner': u'PARTNER2', 'tscript': u'asn_xml2x12_partner2'},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': u'', 'fromeditype': u'xml', 'frommessagetype': u'asn', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'x12', 'tomessagetype': u'856004010', 'topartner': u'PGROUP_A', 'tscript': u'asn_xml2x12_noSSCC'},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': u"simple route: reads x12 856, and write these.\r\nthis route demo's conversion of partnerID's for x12:\r\n- incoming via QUERIES\r\n- outgoing via envelope script. ", 'fromchannel': u'demo_partner_conversion_in', 'fromeditype': u'x12', 'frommessagetype': u'x12', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'demo_partner_conversion', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 1, 'testindicator': u'', 'tochannel': u'demo_partner_conversion_out', 'toeditype': u'', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': u'', 'fromchannel': u'outbound_asn_in', 'fromeditype': u'xml', 'frommessagetype': u'asn', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'outbound_asn', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 1, 'testindicator': u'', 'tochannel': None, 'toeditype': u'', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': u'', 'fromchannel': None, 'fromeditype': u'', 'frommessagetype': u'', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'outbound_asn', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 101, 'testindicator': u'', 'tochannel': u'outbound_asn_out_pgroupA', 'toeditype': u'', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': u'PGROUP_A', 'translateind': 0, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': u'', 'fromchannel': None, 'fromeditype': u'', 'frommessagetype': u'', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'outbound_asn', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 102, 'testindicator': u'', 'tochannel': u'outbound_asn_out_partner2', 'toeditype': u'', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': u'PARTNER2', 'translateind': 0, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': u'', 'fromchannel': None, 'fromeditype': u'', 'frommessagetype': u'', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'outbound_asn', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 103, 'testindicator': u'', 'tochannel': u'outbound_asn_out', 'toeditype': u'', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 0, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'ccodetrigger', 'ccodeid': u'x12_partner', 'ccodeid_desc': u''},
{'plugintype': u'ccode', 'attr1': u'WX', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'x12_partner', 'leftcode': u'FROMPARTNER2', 'rightcode': u'frompartner1'},
{'plugintype': u'ccode', 'attr1': u'YZ', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'x12_partner', 'leftcode': u'TOPARTNER2', 'rightcode': u'topartner1'},
]
