import datetime
version = 2
plugins = [
{'starttls': False, 'ftpaccount': u'', 'rsrv2': None, 'syslock': False, 'rsrv1': None, 'askmdn': u'no', 'inorout': u'in', 'port': 0, 'parameters': u'', 'charset': u'iso-8859-1', 'filename': u'*.edi', 'secret': u'', 'apop': False, 'ftpactive': False, 'type': u'file', 'username': u'', 'idchannel': u'edifactinvoic2json_in', 'mdnchannel': u'', 'ftpbinary': False, 'archivepath': u'', 'host': u'', 'path': u'botssys/infile/edifactinvoic2json/edifact', 'desc': None, 'plugintype': u'channel', 'lockname': u'', 'remove': False, 'sendmdn': u'no'},
{'starttls': False, 'ftpaccount': u'', 'rsrv2': None, 'syslock': False, 'rsrv1': None, 'askmdn': u'no', 'inorout': u'out', 'port': 0, 'parameters': u'', 'charset': u'utf-8', 'filename': u'*.json', 'secret': u'', 'apop': False, 'ftpactive': False, 'type': u'file', 'username': u'', 'idchannel': u'edifactinvoic2json_out', 'mdnchannel': u'', 'ftpbinary': False, 'archivepath': u'', 'host': u'', 'path': u'botssys/outfile/edifactinvoic2json/json', 'desc': None, 'plugintype': u'channel', 'lockname': u'', 'remove': False, 'sendmdn': u'no'},
{'starttls': False, 'ftpaccount': u'', 'rsrv2': None, 'syslock': False, 'rsrv1': None, 'askmdn': u'no', 'inorout': u'in', 'port': 0, 'parameters': u'', 'charset': u'utf-8', 'filename': u'*.json', 'secret': u'', 'apop': False, 'ftpactive': False, 'type': u'file', 'username': u'', 'idchannel': u'jsoninvoic2edifact_in', 'mdnchannel': u'', 'ftpbinary': False, 'archivepath': u'', 'host': u'', 'path': u'botssys/infile/edifactinvoic2json/json', 'desc': None, 'plugintype': u'channel', 'lockname': u'', 'remove': False, 'sendmdn': u'no'},
{'starttls': False, 'ftpaccount': u'', 'rsrv2': None, 'syslock': False, 'rsrv1': None, 'askmdn': u'no', 'inorout': u'out', 'port': 0, 'parameters': u'', 'charset': u'iso-8859-1', 'filename': u'*.edi', 'secret': u'', 'apop': False, 'ftpactive': False, 'type': u'file', 'username': u'', 'idchannel': u'jsoninvoic2edifact_out', 'mdnchannel': u'', 'ftpbinary': False, 'archivepath': u'', 'host': u'', 'path': u'botssys/outfile/edifactinvoic2json/edifact', 'desc': None, 'plugintype': u'channel', 'lockname': u'', 'remove': False, 'sendmdn': u'no'},
{'plugintype': u'translate', 'desc': None, 'frommessagetype': u'INVOICD96AUNEAN008', 'toeditype': u'json', 'rsrv2': None, 'frompartner': None, 'topartner': None, 'rsrv1': None, 'active': True, 'alt': u'', 'fromeditype': u'edifact', 'tscript': u'invoicedi2json', 'tomessagetype': u'jsondemo_invoic'},
{'plugintype': u'translate', 'desc': None, 'frommessagetype': u'jsondemo_invoic', 'toeditype': u'edifact', 'rsrv2': None, 'frompartner': None, 'topartner': None, 'rsrv1': None, 'active': True, 'alt': u'', 'fromeditype': u'json', 'tscript': u'invoicjson2edi', 'tomessagetype': u'INVOICD96AUNEAN008'},
{'defer': False, 'seq': 9999, 'active': True, 'rsrv2': None, 'tomessagetype': u'', 'rsrv1': None, 'alt': u'', 'notindefaultrun': False, 'frompartner': None, 'topartner': None, 'testindicator': u'', 'idroute': u'edifactinvoic2json', 'frommessagetype': u'edifact', 'translateind': True, 'fromchannel': u'edifactinvoic2json_in', 'topartner_tochannel': None, 'toeditype': u'', 'fromeditype': u'edifact', 'desc': None, 'plugintype': u'routes', 'tochannel': u'edifactinvoic2json_out', 'frompartner_tochannel': None},
{'defer': False, 'seq': 9999, 'active': True, 'rsrv2': None, 'tomessagetype': u'', 'rsrv1': None, 'alt': u'', 'notindefaultrun': False, 'frompartner': None, 'topartner': None, 'testindicator': u'', 'idroute': u'jsoninvoic2edifact', 'frommessagetype': u'jsondemo_invoic', 'translateind': True, 'fromchannel': u'jsoninvoic2edifact_in', 'topartner_tochannel': None, 'toeditype': u'', 'fromeditype': u'json', 'desc': None, 'plugintype': u'routes', 'tochannel': u'jsoninvoic2edifact_out', 'frompartner_tochannel': None},
]
