# -*- coding: utf-8 -*-
import datetime
version = '3.1.0'
plugins = [
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'no', 'certfile': None, 'charset': u'us-ascii', 'desc': None, 'filename': u'*.csv', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': True, 'host': u'', 'idchannel': u'csv2edi_in', 'inorout': u'in', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/csvdemo/csv2edi', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'iso-8859-1', 'desc': u'', 'filename': u'*.edi', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': True, 'host': u'', 'idchannel': u'csv2edi_out', 'inorout': u'out', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/csvdemo/csv2edi', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'no', 'certfile': None, 'charset': u'us-ascii', 'desc': None, 'filename': u'*.edi', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': True, 'host': u'', 'idchannel': u'edi2csv_in', 'inorout': u'in', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/csvdemo/edi2csv', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'iso-8859-1', 'desc': u'', 'filename': u'*.csv', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': True, 'host': u'', 'idchannel': u'edi2csv_out', 'inorout': u'out', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/csvdemo/edi2csv', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': u'', 'fromeditype': u'csv', 'frommessagetype': u'csv_orders', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'edifact', 'tomessagetype': u'ORDERSD96AUNEAN008', 'topartner': None, 'tscript': u'csvdemo_csv2edi'},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': u'', 'fromeditype': u'edifact', 'frommessagetype': u'ORDERSD96AUNEAN008', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'csv', 'tomessagetype': u'csv_orders', 'topartner': None, 'tscript': u'csvdemo_edi2csv'},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': u'', 'fromchannel': u'csv2edi_in', 'fromeditype': u'csv', 'frommessagetype': u'csv_orders', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'csv2edi', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 9999, 'testindicator': u'', 'tochannel': u'csv2edi_out', 'toeditype': u'', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': None, 'fromchannel': u'edi2csv_in', 'fromeditype': u'edifact', 'frommessagetype': u'edifact', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'edi2csv', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 9999, 'testindicator': u'', 'tochannel': u'edi2csv_out', 'toeditype': u'', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'ccodetrigger', 'ccodeid': u'artikel', 'ccodeid_desc': None},
{'plugintype': u'ccodetrigger', 'ccodeid': u'test', 'ccodeid_desc': None},
{'plugintype': u'ccode', 'attr1': u'TESTATTR1', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'artikel', 'leftcode': u'TESTIN', 'rightcode': u'TESTOUT'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'artikel', 'leftcode': u'leftcode', 'rightcode': u'rightcode'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'artikel', 'leftcode': u'leftcode2', 'rightcode': u'rightcode'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'artikel', 'leftcode': u'leftcode3', 'rightcode': u'rightcode'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'test', 'leftcode': u'key1', 'rightcode': u'leftcode'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'test', 'leftcode': u'key2', 'rightcode': u'~!@#$%^&*()_+}{:";][=-/.,<>?`'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'test', 'leftcode': u'key3', 'rightcode': u'?\xe9r\xfd\xfa\xed\xf3?\xe1s??lzcn?'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'test', 'leftcode': u'key4', 'rightcode': u'?\xeb?\xff\xfc\xef\xf6\xe4\xb4\xa8???\xe8?\xf9\xec'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'test', 'leftcode': u'key5', 'rightcode': u'\xf2\xe0???UI\xd5\xc3?\xd1`~'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'test', 'leftcode': u'key6', 'rightcode': u'a\xac\u1234\u20ac\u8000'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'test', 'leftcode': u'key7', 'rightcode': u'abc_\u03a0\u03a3\u03a9.txt'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'test', 'leftcode': u'key8', 'rightcode': u'?\xc9R\xdd\xda\xcd\xd3?\xc1S??LZCN??'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'test', 'leftcode': u'key9', 'rightcode': u'\xcb?\xa8Y\xdc\xa8I\xcf\xcf\xd6\xc4???\xc8?\xd9\xcc\xd2`\xc0`Z?'},
]
