# -*- coding: utf-8 -*-
import datetime
version = '3.1.0'
plugins = [
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': None, 'charset': u'iso-8859-1', 'desc': u'', 'filename': u'*', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'demo_xml_envelope_in', 'inorout': u'in', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/demo_xml_envelope/edifact', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': None, 'charset': u'utf-8', 'desc': u'', 'filename': u'*.xml', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'demo_xml_envelope_out', 'inorout': u'out', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/demo_xml_envelope/xml', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': u'', 'fromeditype': u'edifact', 'frommessagetype': u'INVOICD96AUNEAN008', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'xml', 'tomessagetype': u'xmlunit003', 'topartner': None, 'tscript': u'demo_xml_envelope_invoicedi2xml'},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': u'', 'fromchannel': u'demo_xml_envelope_in', 'fromeditype': u'edifact', 'frommessagetype': u'edifact', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'demo_xml_envelope', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 1, 'testindicator': u'', 'tochannel': u'demo_xml_envelope_out', 'toeditype': u'', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
]
