# -*- coding: utf-8 -*-
import datetime
version = '3.1.0'
plugins = [
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'no', 'certfile': None, 'charset': u'iso-8859-1', 'desc': None, 'filename': u'*.edi', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'edifactinvoic2json_in', 'inorout': u'in', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/edifactinvoic2json/edifact', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'no', 'certfile': None, 'charset': u'utf-8', 'desc': None, 'filename': u'*.json', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'edifactinvoic2json_out', 'inorout': u'out', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/edifactinvoic2json/json', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'no', 'certfile': None, 'charset': u'utf-8', 'desc': None, 'filename': u'*.json', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'jsoninvoic2edifact_in', 'inorout': u'in', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/edifactinvoic2json/json', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'no', 'certfile': None, 'charset': u'iso-8859-1', 'desc': None, 'filename': u'*.edi', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'jsoninvoic2edifact_out', 'inorout': u'out', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/edifactinvoic2json/edifact', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': None, 'fromeditype': u'edifact', 'frommessagetype': u'INVOICD96AUNEAN008', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'json', 'tomessagetype': u'jsondemo_invoic', 'topartner': None, 'tscript': u'invoicedi2json'},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': None, 'fromeditype': u'json', 'frommessagetype': u'jsondemo_invoic', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'edifact', 'tomessagetype': u'INVOICD96AUNEAN008', 'topartner': None, 'tscript': u'invoicjson2edi'},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': None, 'fromchannel': u'edifactinvoic2json_in', 'fromeditype': u'edifact', 'frommessagetype': u'edifact', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'edifactinvoic2json', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 9999, 'testindicator': u'', 'tochannel': u'edifactinvoic2json_out', 'toeditype': u'', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': None, 'fromchannel': u'jsoninvoic2edifact_in', 'fromeditype': u'json', 'frommessagetype': u'jsondemo_invoic', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'jsoninvoic2edifact', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 9999, 'testindicator': u'', 'tochannel': u'jsoninvoic2edifact_out', 'toeditype': u'', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
]
