import datetime
version = '3.0.0'
plugins = [
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'us-ascii', 'desc': u'', 'filename': u'*.edi', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'inbound_slsrpt_in', 'inorout': u'in', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/consignment/slsrpt', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'iso-8859-1', 'desc': u'', 'filename': u'slsrpt*.csv', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'inbound_slsrpt_out', 'inorout': u'out', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/consignment/slsrpt', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'iso-8859-1', 'desc': u'', 'filename': u'*.csv', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'outbound_pricat_in', 'inorout': u'in', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/consignment/pricat', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'UNOC', 'desc': u'', 'filename': u'pricat*.edi', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'outbound_pricat_out', 'inorout': u'out', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/consignment/pricat', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': u'', 'fromeditype': u'csv', 'frommessagetype': u'csv_pricat', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'edifact', 'tomessagetype': u'PRICATD96AUNEAN006', 'topartner': None, 'tscript': u'pricat_csv2edifact'},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': u'', 'fromeditype': u'edifact', 'frommessagetype': u'SLSRPTD96AUNEAN004', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'csv', 'tomessagetype': u'csv_slsrpt', 'topartner': None, 'tscript': u'slsrpt_edifact2csv'},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': u'', 'fromchannel': u'inbound_slsrpt_in', 'fromeditype': u'edifact', 'frommessagetype': u'edifact', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'inbound_slsrpt', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 9999, 'testindicator': u'', 'tochannel': u'inbound_slsrpt_out', 'toeditype': u'', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': u'', 'fromchannel': u'outbound_pricat_in', 'fromeditype': u'csv', 'frommessagetype': u'csv_pricat', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'outbound_pricat', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 9999, 'testindicator': u'', 'tochannel': u'outbound_pricat_out', 'toeditype': u'', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
]
