# -*- coding: utf-8 -*-
import datetime
version = '3.1.0'
plugins = [
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'us-ascii', 'desc': u'', 'filename': u'*', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'email_in', 'inorout': u'in', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/confirm/mdn', 'port': 0, 'remove': True, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'mimefile', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'us-ascii', 'desc': u'', 'filename': u'*', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'email_out', 'inorout': u'out', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/confirm/mdn', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'mimefile', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'no', 'certfile': None, 'charset': u'us-ascii', 'desc': None, 'filename': u'*', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'pickup', 'inorout': u'in', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/confirm/sourcemdn', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'utf-8', 'desc': u'', 'filename': u'*', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'trash', 'inorout': u'out', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'trash', 'username': u''},
{'plugintype': u'partner', 'active': True, 'address1': u'', 'address2': u'', 'address3': u'', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'cc': u'', 'city': u'', 'countrycode': u'', 'countrysubdivision': u'', 'desc': u'', 'enddate': None, 'group': [], 'idpartner': u'BOTSTEST1', 'isgroup': False, 'mail': u'bots@test1.com', 'name': u'BOTSTEST1', 'name1': u'', 'name2': u'', 'name3': u'', 'phone1': u'', 'phone2': u'', 'postalcode': u'', 'rsrv1': None, 'rsrv2': None, 'startdate': None},
{'plugintype': u'partner', 'active': True, 'address1': u'', 'address2': u'', 'address3': u'', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'cc': u'', 'city': u'', 'countrycode': u'', 'countrysubdivision': u'', 'desc': u'', 'enddate': None, 'group': [], 'idpartner': u'BOTSTEST2', 'isgroup': False, 'mail': u'bots@test2.com', 'name': u'BOTSTEST2', 'name1': u'', 'name2': u'', 'name3': u'', 'phone1': u'', 'phone2': u'', 'postalcode': u'', 'rsrv1': None, 'rsrv2': None, 'startdate': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': u'', 'fromchannel': u'pickup', 'fromeditype': u'', 'frommessagetype': u'', 'frompartner': u'BOTSTEST1', 'frompartner_tochannel': None, 'idroute': u'1_send_email', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 1, 'testindicator': u'', 'tochannel': u'email_out', 'toeditype': u'', 'tomessagetype': u'', 'topartner': u'BOTSTEST2', 'topartner_tochannel': None, 'translateind': 2, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': u'', 'fromchannel': u'email_in', 'fromeditype': u'raw', 'frommessagetype': u'', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'2_Receive_email_send_mdn', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 1, 'testindicator': u'', 'tochannel': u'trash', 'toeditype': u'raw', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 2, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': u'', 'fromchannel': None, 'fromeditype': u'', 'frommessagetype': u'', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'2_Receive_email_send_mdn', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 2, 'testindicator': u'', 'tochannel': u'email_out', 'toeditype': u'email-confirmation', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 0, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': u"- receive MDN (as send by last route); \r\n- status of 'asked-MDN' is confirmed\r\n- MDN is not further processed.", 'fromchannel': u'email_in', 'fromeditype': u'email-confirmation', 'frommessagetype': u'email', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'3_receive_mdn', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 1, 'testindicator': u'', 'tochannel': None, 'toeditype': u'', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 0, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'confirmrule', 'active': True, 'confirmtype': u'ask-email-MDN', 'editype': u'', 'frompartner': None, 'idchannel': None, 'idroute': None, 'messagetype': u'', 'negativerule': False, 'rsrv1': None, 'rsrv2': None, 'ruletype': u'all', 'topartner': None},
{'plugintype': u'confirmrule', 'active': True, 'confirmtype': u'send-email-MDN', 'editype': u'', 'frompartner': None, 'idchannel': None, 'idroute': None, 'messagetype': u'', 'negativerule': False, 'rsrv1': None, 'rsrv2': None, 'ruletype': u'all', 'topartner': None},
]
