# -*- coding: utf-8 -*-
import datetime
version = '3.1.0'
plugins = [
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'us-ascii', 'desc': u'', 'filename': u'*.fix', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': True, 'host': u'', 'idchannel': u'inbound_edifact_fixedorders_out', 'inorout': u'out', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/demo_composite_route/fixed_orders', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'us-ascii', 'desc': u'', 'filename': u'*.html', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': True, 'host': u'', 'idchannel': u'inbound_edifact_printorders_out', 'inorout': u'out', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/demo_composite_route/print_orders', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'us-ascii', 'desc': u'', 'filename': u'*.csv', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': True, 'host': u'', 'idchannel': u'inbound_edifact_slsrpt_out', 'inorout': u'out', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/demo_composite_route/csv_slsrpt', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'us-ascii', 'desc': u'', 'filename': u'*.edi', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': True, 'host': u'', 'idchannel': u'inbound_edifact_source1', 'inorout': u'in', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/demo_composite_route/source1', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'us-ascii', 'desc': u'', 'filename': u'*.edi', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': True, 'host': u'', 'idchannel': u'inbound_edifact_source2', 'inorout': u'in', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/demo_composite_route/source2', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': u'', 'fromeditype': u'edifact', 'frommessagetype': u'ORDERSD96AUNEAN008', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'fixed', 'tomessagetype': u'ordersfixed', 'topartner': None, 'tscript': u'orders_edifact2fixed'},
{'plugintype': u'translate', 'active': True, 'alt': u'orders_edifact2print', 'desc': u'', 'fromeditype': u'edifact', 'frommessagetype': u'ORDERSD96AUNEAN008', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'templatehtml', 'tomessagetype': u'orders2print', 'topartner': None, 'tscript': u'orders_edifact2print'},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': u'', 'fromeditype': u'edifact', 'frommessagetype': u'SLSRPTD96AUNEAN004', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'csv', 'tomessagetype': u'slsrpt', 'topartner': None, 'tscript': u'slsrpt2csv'},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': u'', 'fromchannel': u'inbound_edifact_source1', 'fromeditype': u'edifact', 'frommessagetype': u'edifact', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'inbound_edifact', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 10, 'testindicator': u'', 'tochannel': None, 'toeditype': u'fixed', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 0, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': u'', 'fromchannel': u'inbound_edifact_source2', 'fromeditype': u'edifact', 'frommessagetype': u'edifact', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'inbound_edifact', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 20, 'testindicator': u'', 'tochannel': None, 'toeditype': u'fixed', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 0, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': u'', 'fromchannel': None, 'fromeditype': u'', 'frommessagetype': u'', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'inbound_edifact', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 100, 'testindicator': u'', 'tochannel': None, 'toeditype': u'fixed', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': u'', 'fromchannel': None, 'fromeditype': u'', 'frommessagetype': u'', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'inbound_edifact', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 1000, 'testindicator': u'', 'tochannel': u'inbound_edifact_fixedorders_out', 'toeditype': u'fixed', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 0, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': u'', 'fromchannel': None, 'fromeditype': u'', 'frommessagetype': u'', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'inbound_edifact', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 1010, 'testindicator': u'', 'tochannel': u'inbound_edifact_printorders_out', 'toeditype': u'templatehtml', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 0, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': u'', 'fromchannel': None, 'fromeditype': u'', 'frommessagetype': u'', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'inbound_edifact', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 1020, 'testindicator': u'', 'tochannel': u'inbound_edifact_slsrpt_out', 'toeditype': u'csv', 'tomessagetype': u'slsrpt', 'topartner': None, 'topartner_tochannel': None, 'translateind': 0, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'ccodetrigger', 'ccodeid': u'aperakrff2qualifer', 'ccodeid_desc': u'BGM.C002.1001 to aperak code'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'aperakrff2qualifer', 'leftcode': u'220', 'rightcode': u'ON'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'aperakrff2qualifer', 'leftcode': u'224', 'rightcode': u'ON'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'aperakrff2qualifer', 'leftcode': u'351', 'rightcode': u'AAK'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'aperakrff2qualifer', 'leftcode': u'35E', 'rightcode': u'AAK'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'aperakrff2qualifer', 'leftcode': u'380', 'rightcode': u'IV'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'aperakrff2qualifer', 'leftcode': u'384', 'rightcode': u'IV'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'aperakrff2qualifer', 'leftcode': u'50E', 'rightcode': u'ON'},
{'plugintype': u'ccode', 'attr1': u'', 'attr2': u'', 'attr3': u'', 'attr4': u'', 'attr5': u'', 'attr6': u'', 'attr7': u'', 'attr8': u'', 'ccodeid': u'aperakrff2qualifer', 'leftcode': u'83', 'rightcode': u'IV'},
]
