# -*- coding: utf-8 -*-
import datetime
version = '3.1.0'
plugins = [
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'no', 'certfile': None, 'charset': u'us-ascii', 'desc': None, 'filename': u'*.edi', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'edifactorder2xmlin', 'inorout': u'in', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/edifactorder2xml/edi', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'no', 'certfile': None, 'charset': u'utf-8', 'desc': None, 'filename': u'*.xml', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'edifactorder2xmlout', 'inorout': u'out', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/edifactorder2xml/xml', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'no', 'certfile': None, 'charset': u'utf-8', 'desc': None, 'filename': u'*.xml', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'xml2edifactorderin', 'inorout': u'in', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/edifactorder2xml/xml', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'no', 'certfile': None, 'charset': u'us-ascii', 'desc': None, 'filename': u'*.edi', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'xml2edifactorderout', 'inorout': u'out', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/edifactorder2xml/edi', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': None, 'fromeditype': u'edifact', 'frommessagetype': u'ORDERSD96AUNEAN008', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'xmlnocheck', 'tomessagetype': u'edifactorder2xml', 'topartner': None, 'tscript': u'edifactorder2xml'},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': None, 'fromeditype': u'xmlnocheck', 'frommessagetype': u'edifactorder2xml', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'edifact', 'tomessagetype': u'ORDERSD96AUNEAN008', 'topartner': None, 'tscript': u'xml2edifactorder'},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': None, 'fromchannel': u'edifactorder2xmlin', 'fromeditype': u'edifact', 'frommessagetype': u'edifact', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'edifactorder2xml', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 9999, 'testindicator': u'', 'tochannel': u'edifactorder2xmlout', 'toeditype': u'', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': None, 'fromchannel': u'xml2edifactorderin', 'fromeditype': u'xmlnocheck', 'frommessagetype': u'edifactorder2xml', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'xml2edifactorder', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 9999, 'testindicator': u'', 'tochannel': u'xml2edifactorderout', 'toeditype': u'', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
]
