# -*- coding: utf-8 -*-
import datetime
version = '3.2.0rc2'
plugins = [
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'us-ascii', 'desc': u'', 'filename': u'*', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'x12_2_xml_in', 'inorout': u'in', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/x12_2_xml', 'port': 0, 'remove': False, 'rsrv1': u'', 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'us-ascii', 'desc': u'', 'filename': u'{messagetype}_*.{editype}', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'x12_2_xml_out', 'inorout': u'out', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/x12_2_xml', 'port': 0, 'remove': False, 'rsrv1': u'', 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'us-ascii', 'desc': u'', 'filename': u'*', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'xml_2_x12_in', 'inorout': u'in', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/xml_2_x12', 'port': 0, 'remove': False, 'rsrv1': u'', 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'us-ascii', 'desc': u'', 'filename': u'{messagetype}_*.{editype}', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'xml_2_x12_out', 'inorout': u'out', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/xml_2_x12', 'port': 0, 'remove': False, 'rsrv1': u'', 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': u'', 'fromeditype': u'x12', 'frommessagetype': u'x12_one2one', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'xmlnocheck', 'tomessagetype': u'x12_one2one', 'topartner': None, 'tscript': u'x12_2_xml'},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': u'', 'fromeditype': u'xmlnocheck', 'frommessagetype': u'x12_one2one', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'x12', 'tomessagetype': u'x12_one2one', 'topartner': None, 'tscript': u'xml_2_x12'},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': u'', 'fromchannel': u'x12_2_xml_in', 'fromeditype': u'x12', 'frommessagetype': u'x12_one2one', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'x12_2_xml', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 1, 'testindicator': u'', 'tochannel': u'x12_2_xml_out', 'toeditype': u'', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': u'', 'fromchannel': u'xml_2_x12_in', 'fromeditype': u'xmlnocheck', 'frommessagetype': u'x12_one2one', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'xml_2_x12', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 1, 'testindicator': u'', 'tochannel': u'xml_2_x12_out', 'toeditype': u'', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
]
