import datetime

plugins = [
{'plugintype': 'routes', 'idroute': u'vendconsignmentcsv2pricat', 'seq': 9999, 'tochannel': u'vendconsigmentpricatout', 'frommessagetype': u'vendconsignmentcsvpricat', 'translateind': True, 'fromchannel': u'vendconsigmentpricatin', 'active': False, 'alt': u'', 'fromeditype': u'csv'},
{'plugintype': 'routes', 'idroute': u'vendconsignmentcsv2pricatdelete', 'seq': 9999, 'tochannel': u'vendconsigmentpricatout', 'frommessagetype': u'vendconsignmentcsvpricat', 'translateind': True, 'fromchannel': u'vendconsigmentpricatdeletein', 'active': False, 'alt': u'pricatdelete', 'fromeditype': u'csv'},
{'plugintype': 'routes', 'idroute': u'vendconsignmentslsrpt2csv', 'seq': 9999, 'tochannel': u'vendconsigmentslsrptout', 'frommessagetype': u'edifact', 'translateind': True, 'fromchannel': u'vendconsigmentslsrptin', 'active': False, 'alt': u'', 'fromeditype': u'edifact'},
{'starttls': False, 'ftpaccount': u'', 'syslock': False, 'askmdn': u'no', 'inorout': u'in', 'port': 0, 'parameters': u'', 'charset': u'us-ascii', 'filename': u'*.edi', 'secret': u'', 'apop': False, 'type': u'file', 'username': u'', 'idchannel': u'vendconsigmentslsrptin', 'mdnchannel': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'path': u'botssys/infile/vendconsignment/slsrpt', 'plugintype': 'channel', 'lockname': u'', 'remove': False, 'sendmdn': u'no'},
{'starttls': False, 'ftpaccount': u'', 'syslock': False, 'askmdn': u'no', 'inorout': u'out', 'port': 0, 'parameters': u'', 'charset': u'iso-8859-1', 'filename': u'slsrpt*.csv', 'secret': u'', 'apop': False, 'type': u'file', 'username': u'', 'idchannel': u'vendconsigmentslsrptout', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'path': u'botssys/outfile/vendconsignment/slsrpt', 'plugintype': 'channel', 'lockname': u'', 'remove': False, 'sendmdn': u'no'},
{'starttls': False, 'ftpaccount': u'', 'syslock': False, 'askmdn': u'no', 'inorout': u'in', 'port': 0, 'parameters': u'', 'charset': u'iso-8859-1', 'filename': u'*.csv', 'secret': u'', 'apop': False, 'type': u'file', 'username': u'', 'idchannel': u'vendconsigmentpricatin', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'path': u'botssys/infile/vendconsignment/pricat', 'plugintype': 'channel', 'lockname': u'', 'remove': False, 'sendmdn': u'no'},
{'starttls': False, 'ftpaccount': u'', 'syslock': False, 'askmdn': u'no', 'inorout': u'in', 'port': 0, 'parameters': u'', 'charset': u'iso-8859-1', 'filename': u'*.csv', 'secret': u'', 'apop': False, 'type': u'file', 'username': u'', 'idchannel': u'vendconsigmentpricatdeletein', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'path': u'botssys/infile/vendconsignment/pricatdelete', 'plugintype': 'channel', 'lockname': u'', 'remove': False, 'sendmdn': u'no'},
{'starttls': False, 'ftpaccount': u'', 'syslock': False, 'askmdn': u'no', 'inorout': u'out', 'port': 0, 'parameters': u'', 'charset': u'UNOC', 'filename': u'pricat*.edi', 'secret': u'', 'apop': False, 'type': u'file', 'username': u'', 'idchannel': u'vendconsigmentpricatout', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'path': u'botssys/outfile/vendconsignment/pricat', 'plugintype': 'channel', 'lockname': u'', 'remove': False, 'sendmdn': u'no'},
{'plugintype': 'translate', 'frommessagetype': u'SLSRPTD96AUNEAN004', 'toeditype': u'csv', 'frompartner': u'', 'topartner': u'', 'active': True, 'alt': u'', 'fromeditype': u'edifact', 'tscript': u'vendconsignmentslsrpt2csv', 'tomessagetype': u'vendconsignmentcsvslsrpt'},
{'plugintype': 'translate', 'frommessagetype': u'vendconsignmentcsvpricat', 'toeditype': u'edifact', 'frompartner': u'', 'topartner': u'', 'active': True, 'alt': u'', 'fromeditype': u'csv', 'tscript': u'vendconsignmentcsv2pricat', 'tomessagetype': u'PRICATD96AUNEAN006'},
{'plugintype': 'translate', 'frommessagetype': u'vendconsignmentcsvpricat', 'toeditype': u'edifact', 'frompartner': u'', 'topartner': u'', 'active': True, 'alt': u'pricatdelete', 'fromeditype': u'csv', 'tscript': u'vendconsignmentcsv2pricatdelete', 'tomessagetype': u'PRICATD96AUNEAN006'},
{'ccodeid': u'adres', 'leftcode': u'8711793000000', 'plugintype': 'ccode', 'rightcode': u'VROOM & DREESMANN (NAD+BY en UNB)'},
{'ccodeid': u'adres', 'leftcode': u'8711793000017', 'plugintype': 'ccode', 'rightcode': u'FACTUURADRES      (NAD+IV)'},
{'ccodeid': u'adres', 'leftcode': u'8711793000024', 'plugintype': 'ccode', 'rightcode': u'ALKMAAR'},
{'ccodeid': u'adres', 'leftcode': u'8715751617170', 'plugintype': 'ccode', 'rightcode': u'Almere Nieuw'},
{'ccodeid': u'adres', 'leftcode': u'8711793000048', 'plugintype': 'ccode', 'rightcode': u'ALPHEN'},
{'ccodeid': u'adres', 'leftcode': u'8711793000055', 'plugintype': 'ccode', 'rightcode': u'AMERSFOORT'},
{'ccodeid': u'adres', 'leftcode': u'8711793000062', 'plugintype': 'ccode', 'rightcode': u'AMSTELVEEN'},
{'ccodeid': u'adres', 'leftcode': u'8711793000086', 'plugintype': 'ccode', 'rightcode': u'AMSTERDAM KALVERSTRAAT'},
{'ccodeid': u'adres', 'leftcode': u'8711793000109', 'plugintype': 'ccode', 'rightcode': u'AMSTERDAM NOORD'},
{'ccodeid': u'adres', 'leftcode': u'8711793000116', 'plugintype': 'ccode', 'rightcode': u'APELDOORN'},
{'ccodeid': u'adres', 'leftcode': u'8711793000123', 'plugintype': 'ccode', 'rightcode': u'ARNHEM'},
{'ccodeid': u'adres', 'leftcode': u'8711793000130', 'plugintype': 'ccode', 'rightcode': u'ASSEN'},
{'ccodeid': u'adres', 'leftcode': u'8711793000147', 'plugintype': 'ccode', 'rightcode': u'BERGEN OP ZOOM'},
{'ccodeid': u'adres', 'leftcode': u'8711793000154', 'plugintype': 'ccode', 'rightcode': u'BEVERWIJK'},
{'ccodeid': u'adres', 'leftcode': u'8711793000161', 'plugintype': 'ccode', 'rightcode': u'BREDA'},
{'ccodeid': u'adres', 'leftcode': u'8711793000697', 'plugintype': 'ccode', 'rightcode': u'DC ADUARD'},
{'ccodeid': u'adres', 'leftcode': u'8711793000635', 'plugintype': 'ccode', 'rightcode': u'DC AMSTERDAM'},
{'ccodeid': u'adres', 'leftcode': u'8711793000734', 'plugintype': 'ccode', 'rightcode': u'DC DE MEERN'},
{'ccodeid': u'adres', 'leftcode': u'8711793000659', 'plugintype': 'ccode', 'rightcode': u'DC LEEK'},
{'ccodeid': u'adres', 'leftcode': u'8711793000673', 'plugintype': 'ccode', 'rightcode': u'DC ST.OEDENRODE'},
{'ccodeid': u'adres', 'leftcode': u'8711793000710', 'plugintype': 'ccode', 'rightcode': u'DC UTRECHT'},
{'ccodeid': u'adres', 'leftcode': u'8715751220226', 'plugintype': 'ccode', 'rightcode': u'DC V&D TV'},
{'ccodeid': u'adres', 'leftcode': u'8711793000178', 'plugintype': 'ccode', 'rightcode': u'DELFT'},
{'ccodeid': u'adres', 'leftcode': u'8711793000185', 'plugintype': 'ccode', 'rightcode': u'DEN BOSCH'},
{'ccodeid': u'adres', 'leftcode': u'8711793000192', 'plugintype': 'ccode', 'rightcode': u'DEN HAAG LEYWEG'},
{'ccodeid': u'adres', 'leftcode': u'8711793000208', 'plugintype': 'ccode', 'rightcode': u'DEN HAAG SPUI'},
{'ccodeid': u'adres', 'leftcode': u'8711793000215', 'plugintype': 'ccode', 'rightcode': u'DEN HELDER'},
{'ccodeid': u'adres', 'leftcode': u'8711793000222', 'plugintype': 'ccode', 'rightcode': u'DEVENTER'},
{'ccodeid': u'adres', 'leftcode': u'8715751613677', 'plugintype': 'ccode', 'rightcode': u'DOETINCHEM'},
{'ccodeid': u'adres', 'leftcode': u'8711793000239', 'plugintype': 'ccode', 'rightcode': u'DORDRECHT'},
{'ccodeid': u'adres', 'leftcode': u'8711793001441', 'plugintype': 'ccode', 'rightcode': u'EDE'},
{'ccodeid': u'adres', 'leftcode': u'8711793000246', 'plugintype': 'ccode', 'rightcode': u'EINDHOVEN'},
{'ccodeid': u'adres', 'leftcode': u'8711793000253', 'plugintype': 'ccode', 'rightcode': u'EMMEN'},
{'ccodeid': u'adres', 'leftcode': u'8711793000260', 'plugintype': 'ccode', 'rightcode': u'ENSCHEDE'},
{'ccodeid': u'adres', 'leftcode': u'8711793000772', 'plugintype': 'ccode', 'rightcode': u'GOES'},
{'ccodeid': u'adres', 'leftcode': u'8715751220240', 'plugintype': 'ccode', 'rightcode': u'GORINCHEM'},
{'ccodeid': u'adres', 'leftcode': u'8711793000284', 'plugintype': 'ccode', 'rightcode': u'GOUDA'},
{'ccodeid': u'adres', 'leftcode': u'8711793000291', 'plugintype': 'ccode', 'rightcode': u'GRONINGEN'},
{'ccodeid': u'adres', 'leftcode': u'8711793000307', 'plugintype': 'ccode', 'rightcode': u'HAARLEM CENTRUM'},
{'ccodeid': u'adres', 'leftcode': u'8711793000314', 'plugintype': 'ccode', 'rightcode': u'HAARLEM SCHALKWIJK'},
{'ccodeid': u'adres', 'leftcode': u'8711793000321', 'plugintype': 'ccode', 'rightcode': u'HEERLEN'},
{'ccodeid': u'adres', 'leftcode': u'8715751360007', 'plugintype': 'ccode', 'rightcode': u'HELLEVOETSLUIS'},
{'ccodeid': u'adres', 'leftcode': u'8711793001472', 'plugintype': 'ccode', 'rightcode': u'HENGELO'},
{'ccodeid': u'adres', 'leftcode': u'8711793000345', 'plugintype': 'ccode', 'rightcode': u'HILVERSUM'},
{'ccodeid': u'adres', 'leftcode': u'8711793001427', 'plugintype': 'ccode', 'rightcode': u'HOOFDDORP'},
{'ccodeid': u'adres', 'leftcode': u'8711793000352', 'plugintype': 'ccode', 'rightcode': u'HOORN'},
{'ccodeid': u'adres', 'leftcode': u'8711793000376', 'plugintype': 'ccode', 'rightcode': u'LEEUWARDEN'},
{'ccodeid': u'adres', 'leftcode': u'8711793000383', 'plugintype': 'ccode', 'rightcode': u'LEIDEN'},
{'ccodeid': u'adres', 'leftcode': u'8711793000390', 'plugintype': 'ccode', 'rightcode': u'LEIDSCHENDAM'},
{'ccodeid': u'adres', 'leftcode': u'8711793000406', 'plugintype': 'ccode', 'rightcode': u'MAASTRICHT'},
{'ccodeid': u'adres', 'leftcode': u'8715751220257', 'plugintype': 'ccode', 'rightcode': u'MEPPEL'},
{'ccodeid': u'adres', 'leftcode': u'8711793000703', 'plugintype': 'ccode', 'rightcode': u'MG ADUARD'},
{'ccodeid': u'adres', 'leftcode': u'8711793000642', 'plugintype': 'ccode', 'rightcode': u'MG AMSTERDAM'},
{'ccodeid': u'adres', 'leftcode': u'8711793000666', 'plugintype': 'ccode', 'rightcode': u'MG DEN HAAG'},
{'ccodeid': u'adres', 'leftcode': u'8711793000741', 'plugintype': 'ccode', 'rightcode': u'MG NIJMEGEN'},
{'ccodeid': u'adres', 'leftcode': u'8711793000680', 'plugintype': 'ccode', 'rightcode': u'MG ST.OEDENRODE'},
{'ccodeid': u'adres', 'leftcode': u'8711793000727', 'plugintype': 'ccode', 'rightcode': u'MG UTRECHT'},
{'ccodeid': u'adres', 'leftcode': u'8715751137432', 'plugintype': 'ccode', 'rightcode': u'MONSTERVESTIGING'},
{'ccodeid': u'adres', 'leftcode': u'8711793001465', 'plugintype': 'ccode', 'rightcode': u'NAALDWIJK'},
{'ccodeid': u'adres', 'leftcode': u'8711793000420', 'plugintype': 'ccode', 'rightcode': u'NIJMEGEN'},
{'ccodeid': u'adres', 'leftcode': u'8711793001403', 'plugintype': 'ccode', 'rightcode': u'OOSTERHOUT'},
{'ccodeid': u'adres', 'leftcode': u'8711793000437', 'plugintype': 'ccode', 'rightcode': u'OSS'},
{'ccodeid': u'adres', 'leftcode': u'8711793000758', 'plugintype': 'ccode', 'rightcode': u'RESERVE'},
{'ccodeid': u'adres', 'leftcode': u'8711793000765', 'plugintype': 'ccode', 'rightcode': u'RESERVE'},
{'ccodeid': u'adres', 'leftcode': u'8711793001489', 'plugintype': 'ccode', 'rightcode': u'PURMEREND'},
{'ccodeid': u'adres', 'leftcode': u'8711793000444', 'plugintype': 'ccode', 'rightcode': u'RIJSWIJK'},
{'ccodeid': u'adres', 'leftcode': u'8711793000451', 'plugintype': 'ccode', 'rightcode': u'ROERMOND'},
{'ccodeid': u'adres', 'leftcode': u'8711793000468', 'plugintype': 'ccode', 'rightcode': u'ROOSENDAAL'},
{'ccodeid': u'adres', 'leftcode': u'8711793000475', 'plugintype': 'ccode', 'rightcode': u'ROTTERDAM BEURSPLEIN'},
{'ccodeid': u'adres', 'leftcode': u'8711793000482', 'plugintype': 'ccode', 'rightcode': u'ROTTERDAM ZUIDPLEIN'},
{'ccodeid': u'adres', 'leftcode': u'8711793000499', 'plugintype': 'ccode', 'rightcode': u'SITTARD'},
{'ccodeid': u'adres', 'leftcode': u'8711793000529', 'plugintype': 'ccode', 'rightcode': u'TILBURG'},
{'ccodeid': u'adres', 'leftcode': u'8711793000536', 'plugintype': 'ccode', 'rightcode': u'UTRECHT'},
{'ccodeid': u'adres', 'leftcode': u'8715751220233', 'plugintype': 'ccode', 'rightcode': u'V&D TV'},
{'ccodeid': u'adres', 'leftcode': u'8711793001434', 'plugintype': 'ccode', 'rightcode': u'VEENENDAAL'},
{'ccodeid': u'adres', 'leftcode': u'8711793001410', 'plugintype': 'ccode', 'rightcode': u'WEERT'},
{'ccodeid': u'adres', 'leftcode': u'8711793000574', 'plugintype': 'ccode', 'rightcode': u'ZAANDAM'},
{'ccodeid': u'adres', 'leftcode': u'8711793000581', 'plugintype': 'ccode', 'rightcode': u'ZEIST'},
{'ccodeid': u'adres', 'leftcode': u'8711793000611', 'plugintype': 'ccode', 'rightcode': u'ZOETERMEER'},
{'ccodeid': u'adres', 'leftcode': u'8711793000598', 'plugintype': 'ccode', 'rightcode': u'ZWOLLE'},
]
