# -*- coding: utf-8 -*-
import datetime
version = '3.1.0'
plugins = [
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'us-ascii', 'desc': u'', 'filename': u'*', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': True, 'host': u'', 'idchannel': u'inbound_edifact_in', 'inorout': u'in', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/demo_idoc/inbound_edifact', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'us-ascii', 'desc': u'', 'filename': u'*.idoc', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': True, 'host': u'', 'idchannel': u'inbound_edifact_out', 'inorout': u'out', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/demo_idoc/idoc_orders', 'port': 0, 'remove': True, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'us-ascii', 'desc': u'', 'filename': u'*.idoc', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': True, 'host': u'', 'idchannel': u'outbound_orders_in', 'inorout': u'in', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/demo_idoc/1201ORDERS01', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'UNOC', 'desc': u'', 'filename': u'*.edi', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': True, 'host': u'', 'idchannel': u'outbound_orders_out', 'inorout': u'out', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/demo_idoc/edifact_orders', 'port': 0, 'remove': True, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'us-ascii', 'desc': u'', 'filename': u'*.idoc', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': True, 'host': u'', 'idchannel': u'outbound_pricat_in', 'inorout': u'in', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/demo_idoc/1205WP_PLU02', 'port': 0, 'remove': False, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'', 'askmdn': u'', 'certfile': u'', 'charset': u'UNOC', 'desc': u'', 'filename': u'*.edi', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': True, 'host': u'', 'idchannel': u'outbound_pricat_out', 'inorout': u'out', 'keyfile': u'', 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/demo_idoc/edifact_pricat', 'port': 0, 'remove': True, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': None, 'fromeditype': u'edifact', 'frommessagetype': u'ORDERSD96AUNEAN008', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'idoc', 'tomessagetype': u'ORDERS01', 'topartner': None, 'tscript': u'ORDERSD96A2ORDERS01'},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': None, 'fromeditype': u'edifact', 'frommessagetype': u'PRICATD96AUNEAN005', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'idoc', 'tomessagetype': u'WP_PLU02', 'topartner': None, 'tscript': u'PRICATD96A2WP_PLU02'},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': None, 'fromeditype': u'idoc', 'frommessagetype': u'ORDERS01', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'edifact', 'tomessagetype': u'ORDERSD96AUNEAN008', 'topartner': None, 'tscript': u'ORDERS012ORDERSD96A'},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': None, 'fromeditype': u'idoc', 'frommessagetype': u'WP_PLU02', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'edifact', 'tomessagetype': u'PRICATD96AUNEAN005', 'topartner': None, 'tscript': u'WP_PLU022PRICATD96A'},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': u'', 'fromchannel': u'inbound_edifact_in', 'fromeditype': u'edifact', 'frommessagetype': u'edifact', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'inbound_orders_edifact2idoc', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 9999, 'testindicator': u'', 'tochannel': u'inbound_edifact_out', 'toeditype': u'', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': u'', 'fromchannel': u'outbound_orders_in', 'fromeditype': u'idoc', 'frommessagetype': u'ORDERS01', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'outbound_orders_idoc2edifact', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 9999, 'testindicator': u'', 'tochannel': u'outbound_orders_out', 'toeditype': u'', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': u'', 'fromchannel': u'outbound_pricat_in', 'fromeditype': u'idoc', 'frommessagetype': u'WP_PLU02', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'outbound_pricat_idoc2edifact', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 9999, 'testindicator': u'', 'tochannel': u'outbound_pricat_out', 'toeditype': u'', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
]
