import datetime

plugins = [
{'plugintype': 'routes', 'idroute': u'Alto_invoices', 'seq': 10L, 'notindefaultrun': False, 'tochannel': u'DISCARD', 'frommessagetype': u'ALTO_INVHDR', 'translateind': True, 'fromchannel': u'alto_header_in', 'active': False, 'fromeditype': u'csv'},
{'plugintype': 'routes', 'idroute': u'Alto_invoices', 'seq': 20L, 'notindefaultrun': False, 'tochannel': u'alto_out', 'frommessagetype': u'ALTO_INVDTL', 'translateind': True, 'fromchannel': u'alto_detail_in', 'active': False, 'fromeditype': u'csv'},
{'starttls': False, 'archivepath': u'', 'ftpaccount': u'', 'syslock': False, 'askmdn': u'no', 'inorout': u'out', 'port': 0L, 'parameters': u'', 'charset': u'us-ascii', 'filename': u'*', 'secret': u'', 'apop': False, 'type': u'file', 'username': u'', 'idchannel': u'DISCARD', 'mdnchannel': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'path': u'botssys/outfile/alto/DISCARD', 'plugintype': 'channel', 'lockname': u'', 'remove': False, 'sendmdn': u'no'},
{'starttls': False, 'archivepath': u'', 'ftpaccount': u'', 'syslock': False, 'askmdn': u'no', 'inorout': u'in', 'port': 0L, 'parameters': u'', 'charset': u'us-ascii', 'filename': u'*DTL.csv', 'secret': u'', 'apop': False, 'type': u'file', 'username': u'', 'idchannel': u'alto_detail_in', 'mdnchannel': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'path': u'botssys/infile/alto', 'plugintype': 'channel', 'lockname': u'', 'remove': False, 'sendmdn': u'no'},
{'starttls': False, 'archivepath': u'', 'ftpaccount': u'', 'syslock': False, 'askmdn': u'no', 'inorout': u'in', 'port': 0L, 'parameters': u'', 'charset': u'us-ascii', 'filename': u'*HDR.csv', 'secret': u'', 'apop': False, 'type': u'file', 'username': u'', 'idchannel': u'alto_header_in', 'mdnchannel': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'path': u'botssys/infile/alto', 'plugintype': 'channel', 'lockname': u'', 'remove': False, 'sendmdn': u'no'},
{'starttls': False, 'archivepath': u'', 'ftpaccount': u'', 'syslock': False, 'askmdn': u'no', 'inorout': u'out', 'port': 0L, 'parameters': u'', 'charset': u'us-ascii', 'filename': u'*', 'secret': u'', 'apop': False, 'type': u'file', 'username': u'', 'idchannel': u'alto_out', 'mdnchannel': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'path': u'botssys/outfile/alto/out', 'plugintype': 'channel', 'lockname': u'', 'remove': False, 'sendmdn': u'no'},
{'plugintype': 'translate', 'frommessagetype': u'ALTO_INVHDR', 'toeditype': u'csv', 'frompartner': u'', 'topartner': u'', 'active': True, 'alt': u'', 'fromeditype': u'csv', 'tscript': u'ALTO_INVHDR', 'tomessagetype': u'ALTO_INVHDR'},
{'plugintype': 'translate', 'frommessagetype': u'ALTO_INVDTL', 'toeditype': u'idoc', 'frompartner': u'', 'topartner': u'', 'active': True, 'alt': u'', 'fromeditype': u'csv', 'tscript': u'ALTO_INVDTL', 'tomessagetype': u'INVOIC02'},
]
